# Site settings
title: Capriatto
email: oky.capriatto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este es mi blog personal sobre tecnología e ingeniería en sistemas y computación donde muestro como bitácora todas las experiencias y temas que me agradan y quiero compartir con el mundo.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://capriatto.github.io" # the base hostname & protocol for your site
twitter_username: oky_capriatto
github_username:  Capriatto

# Build settings
markdown: kramdown
